import warnings

packetspec = [
    {
        "array": "TIME_SYNC",
        "id": 4,
        "name": "TIME_SYNC_TYPE",
        "numeric": True,
        "size": 18,
        "struct": "<2IQ",
    },
    {
        "array": "ECG_I",
        "id": 5,
        "name": "ECG_CHANNEL00_DATA_TYPE",
        "numeric": False,
        "size": 510,
        "struct": "<2I125i",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "ECG_II",
        "id": 6,
        "name": "ECG_CHANNEL01_DATA_TYPE",
        "numeric": False,
        "size": 510,
        "struct": "<2I125i",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "ECG_III",
        "id": 7,
        "name": "ECG_CHANNEL02_DATA_TYPE",
        "numeric": False,
        "size": 510,
        "struct": "<2I125i",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "ECG_AVR",
        "id": 8,
        "name": "ECG_CHANNEL03_DATA_TYPE",
        "numeric": False,
        "size": 510,
        "struct": "<2I125i",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "ECG_AVL",
        "id": 9,
        "name": "ECG_CHANNEL04_DATA_TYPE",
        "numeric": False,
        "size": 510,
        "struct": "<2I125i",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "ECG_AVF",
        "id": 10,
        "name": "ECG_CHANNEL05_DATA_TYPE",
        "numeric": False,
        "size": 510,
        "struct": "<2I125i",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "ECG_V",
        "id": 11,
        "name": "ECG_CHANNEL06_DATA_TYPE",
        "numeric": False,
        "size": 510,
        "struct": "<2I125i",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "ECG_V2",
        "id": 12,
        "name": "ECG_CHANNEL07_DATA_TYPE",
        "numeric": False,
        "size": 510,
        "struct": "<2I125i",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "ECG_V3",
        "id": 13,
        "name": "ECG_CHANNEL08_DATA_TYPE",
        "numeric": False,
        "size": 510,
        "struct": "<2I125i",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "ECG_V4",
        "id": 14,
        "name": "ECG_CHANNEL09_DATA_TYPE",
        "numeric": False,
        "size": 510,
        "struct": "<2I125i",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "ECG_V5",
        "id": 15,
        "name": "ECG_CHANNEL10_DATA_TYPE",
        "numeric": False,
        "size": 510,
        "struct": "<2I125i",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "ECG_V6",
        "id": 16,
        "name": "ECG_CHANNEL11_DATA_TYPE",
        "numeric": False,
        "size": 510,
        "struct": "<2I125i",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "HR",
        "id": 17,
        "name": "HR_DATA_TYPE",
        "numeric": True,
        "size": 12,
        "struct": "<2IH",
    },
    {
        "array": "BP_PKT",
        "id": 18,
        "name": "BP_DATA_TYPE",
        "numeric": True,
        "size": 24,
        "struct": "<3I4H2B",
    },
    {
        "array": "BP",
        "id": 36,
        "name": "BP_DATA2_TYPE",
        "numeric": True,
        "size": 18,
        "struct": "<2I4H",
    },
    {
        "array": "RR",
        "id": 19,
        "name": "RESP_DATA_TYPE",
        "numeric": True,
        "size": 12,
        "struct": "<2IH",
    },
    {
        "array": "SPO2",
        "id": 20,
        "name": "SPO2_DATA_TYPE",
        "numeric": True,
        "size": 16,
        "struct": "<2I3H",
    },
    {
        "array": "TEMP",
        "id": 21,
        "name": "TEMP_DATA_TYPE",
        "numeric": True,
        "size": 12,
        "struct": "<2IH",
    },
    {
        "array": "ACC_ECG",
        "id": 37,
        "name": "ACC_ECG_TYPE",
        "numeric": False,
        "size": 160,
        "struct": "<2I75h",
        "waveform": {"channels": 3, "rows": 25, "sf": 50, "version": 0},
    },
    {
        "array": "ACC_ARM",
        "id": 38,
        "name": "ACC_ARM_TYPE",
        "numeric": False,
        "size": 160,
        "struct": "<2I75h",
        "waveform": {"channels": 3, "rows": 25, "sf": 50, "version": 0},
    },
    {
        "array": "ACC_WRT",
        "id": 39,
        "name": "ACC_WT_TYPE",
        "numeric": False,
        "size": 160,
        "struct": "<2I75h",
        "waveform": {"channels": 3, "rows": 25, "sf": 50, "version": 0},
    },
    {
        "array": "RED_AC",
        "id": 44,
        "name": "SERVER_TYPE_PPG_WAVE_RED_AC_TYPE",
        "numeric": False,
        "size": 260,
        "struct": "<2I125H",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "RED_DC",
        "id": 45,
        "name": "SERVER_TYPE_PPG_WAVE_RED_DC_TYPE",
        "numeric": False,
        "size": 260,
        "struct": "<2I125H",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "IR_AC",
        "id": 46,
        "name": "SERVER_TYPE_PPG_WAVE_IR_AC_TYPE",
        "numeric": False,
        "size": 260,
        "struct": "<2I125H",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "IR_DC",
        "id": 47,
        "name": "SERVER_TYPE_PPG_WAVE_IR_DC_TYPE",
        "numeric": False,
        "size": 260,
        "struct": "<2I125H",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "AMBIENT",
        "id": 48,
        "name": "SERVER_TYPE_PPG_WAVE_AMBIENT_TYPE",
        "numeric": False,
        "size": 260,
        "struct": "<2I125H",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "PR",
        "id": 49,
        "name": "PPG_PR_DATA_TYPE",
        "numeric": True,
        "size": 12,
        "struct": "<2IH",
    },
    {
        "array": "OSC",
        "id": 50,
        "name": "SERVER_TYPE_CUFF_WAVE_OSC_TYPE",
        "numeric": False,
        "size": 260,
        "struct": "<2I125H",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "P1",
        "id": 51,
        "name": "SERVER_TYPE_CUFF_WAVE_PRI_TYPE",
        "numeric": False,
        "size": 260,
        "struct": "<2I125H",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "P2",
        "id": 52,
        "name": "SERVER_TYPE_CUFF_WAVE_SEC_TYPE",
        "numeric": False,
        "size": 260,
        "struct": "<2I125H",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "SPO2_CTRL",
        "id": 54,
        "name": "SPO2_CONTROL_PACKET_TYPE",
        "numeric": True,
        "size": 18,
        "struct": "<2I2H2BH",
    },
    {
        "array": "IP",
        "id": 55,
        "name": "RESP_WAVEFORM_TYPE",
        "numeric": False,
        "size": 110,
        "struct": "<2I25i",
        "waveform": {"channels": 1, "rows": 25, "sf": 50, "version": 0},
    },
    {
        "array": "IR_FILT",
        "id": 56,
        "name": "FILTEREDPPG_WAVE_IR_AC_TYPE",
        "numeric": False,
        "size": 510,
        "struct": "<2I125i",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "RED_FILT",
        "id": 57,
        "name": "FILTEREDPPG_WAVE_RED_AC_TYPE",
        "numeric": False,
        "size": 510,
        "struct": "<2I125i",
        "waveform": {"channels": 1, "rows": 125, "sf": 500, "version": 0},
    },
    {
        "array": "PAT_PKT",
        "id": 58,
        "name": "PTT_DATA_TYPE",
        "numeric": True,
        "size": 28,
        "struct": "<5I2H2b",
    },
    {
        "array": "CNIBP_CAL_PKT",
        "id": 188,
        "name": "CNIBP_CALIBRATION_DATA_V2_TYPE",
        "numeric": True,
        "size": 60,
        "struct": "<3Ih3H2hH2h2iI4h2f",
    },
    {
        "array": "CNIBP",
        "id": 189,
        "name": "CNIBP_NUMERIC_V2",
        "numeric": True,
        "size": 28,
        "struct": "<3I6hH",
    },
    {
        "array": "ARM_HT_PKT",
        "id": 190,
        "name": "ARM_HEIGHT_DATA_TYPE",
        "numeric": True,
        "size": 22,
        "struct": "<3I4h",
    },
    {
        "array": "POSTURE_PKT",
        "id": 191,
        "name": "POSTURE_DATA_TYPE",
        "numeric": True,
        "size": 24,
        "struct": "<3I5h",
    },
    {
        "array": "PPG_BEAT_PKT",
        "id": 193,
        "name": "PPG_BEAT_PICK_TYPE",
        "numeric": True,
        "size": 55,
        "struct": "<5I4H6ib",
    },
    {
        "array": "PPG_DEBUG_PKT",
        "id": 194,
        "name": "PPG_DEBUG_TYPE",
        "numeric": True,
        "size": 52,
        "struct": "<6IB3IB3I",
    },
    {
        "array": "ACC_ECG_500",
        "id": 197,
        "name": "ACC_ECG2_TYPE",
        "numeric": False,
        "size": 460,
        "struct": "<2I225h",
        "waveform": {"channels": 3, "rows": 75, "sf": 500, "version": 0},
    },
    {
        "array": "MON_GLOBALBEAT_PKT",
        "id": 199,
        "name": "TYPE_ECG_GLOBAL_BEAT",
        "numeric": True,
        "size": 42,
        "struct": "<2I15Hh",
    },
    {
        "array": "MON_ARRHYTHMIA_PKT",
        "id": 200,
        "name": "ARRHYTHMIA_EVENT",
        "numeric": True,
        "size": 29,
        "struct": "<2IB8Hh",
    },
    {
        "array": "MON_BEAT_PKT",
        "id": 201,
        "name": "ARRHYTHMIA_BEAT",
        "numeric": True,
        "size": 11,
        "struct": "<2Ib",
    },
    {
        "array": "MON_HR",
        "id": 202,
        "name": "MON_NUMERIC_PKT",
        "numeric": True,
        "size": 18,
        "struct": "<2IH6B",
    },
    {
        "array": "SCG",
        "id": 205,
        "name": "SCG_WAVEFORM_PKT",
        "numeric": False,
        "size": 516,
        "struct": "<2I2B252h",
        "waveform": {"channels": 3, "rows": 84, "sf": 500, "version": 1},
    },
    {
        "array": "CNIBP",
        "id": 208,
        "name": "CNIBP_NUMERIC_V3",
        "numeric": True,
        "size": 42,
        "struct": "<2II6hH3hII",
    },
    {"id": 1880, "name": "PROVISIONING_NOTIFICATION_TYPE", "numeric": False, "size": 8},
    {"id": 1, "name": "PROVISIONING_TYPE", "numeric": False, "size": 8},
    {"id": 2, "name": "PROVISIONING_RESPONSE_TYPE", "numeric": False, "size": 30},
    {"id": 192, "name": "PROVISIONING2_TYPE", "numeric": False, "size": 140},
    {"id": 198, "name": "PROVISIONING3_TYPE", "numeric": False, "size": 140},
    {
        "array": "ALARMS",
        "id": 184,
        "name": "ALARM_STATE_DATA2_TYPE",
        "header": {"struct": "<H2IB2IB", "size": 20},
        "numeric": True,
        "size": 0,
    },
    {"id": 23, "name": "ALARM_COMMAND_TYPE", "numeric": False, "size": 7},
    {
        "array": "ALARM_LIMITS",
        "id": 186,
        "name": "ALARM_LIMITS2_TYPE",
        "header": {"struct": "<H2IH", "size": 12},
        "numeric": False,
        "size": 0,
    },
    {"id": 25, "name": "ALARM_PARAMETERS_TYPE", "numeric": False, "size": 0},
    {"id": 195, "name": "POSTURE_ALARM_SETTINGS_TYPE", "numeric": False, "size": 14},
    {"id": 196, "name": "INACTIVITY_ALARM_SETTINGS_TYPE", "numeric": False, "size": 14},
    {"id": 26, "name": "CARE_GUIDE_SMO2_DATA_TYPE", "numeric": False, "size": 14},
    {"id": 27, "name": "CARE_GUIDE_PH_DATA_TYPE", "numeric": False, "size": 14},
    {"id": 28, "name": "CARE_GUIDE_HCT_DATA_TYPE", "numeric": False, "size": 14},
    {"id": 1820, "name": "COMPONENT_HEARTBEAT_TYPE", "numeric": False, "size": 8},
    {"id": 61, "name": "PING_TYPE", "numeric": False, "size": 6},
    {"id": 62, "name": "SOFTWARE_UPDATE_REQUEST_TYPE", "numeric": False, "size": 8},
    {
        "id": 65,
        "name": "SOFTWARE_UPDATE_VERSION_REQUEST_TYPE",
        "numeric": False,
        "size": 6,
    },
    {"id": 67, "name": "BACKLOG_STOP_TYPE", "numeric": False, "size": 6},
    {"id": 68, "name": "NETWORK_CONFIG_REQUEST_TYPE", "numeric": False, "size": 2},
    {"id": 71, "name": "DEVICE_BUMP_TYPE", "numeric": False, "size": 45},
    {
        "id": 181,
        "name": "PATIENT_ASSIGNMENT_RESPONSE_TYPE",
        "numeric": False,
        "size": 11,
    },
    {"id": 187, "name": "SESSION_MANAGEMENT_TYPE", "numeric": False, "size": 36},
    {"id": 1840, "name": "DEVICE_SWAP_NOTIFICATION_TYPE", "numeric": False, "size": 70},
    {"id": 1890, "name": "SESSION_COMMAND_TYPE", "numeric": False, "size": 15},
    {"id": 1900, "name": "SESSION_REQUEST_TYPE", "numeric": False, "size": 15},
    {"id": 3, "name": "LOCATOR_TYPE", "numeric": False, "size": 0},
    {"id": 63, "name": "SOFTWARE_UPDATE_RESPONSE_TYPE", "numeric": False, "size": 0},
    {"id": 64, "name": "SOFTWARE_UPDATE_CHUNK_TYPE", "numeric": False, "size": 0},
    {
        "id": 66,
        "name": "SOFTWARE_UPDATE_VERSION_RESPONSE_TYPE",
        "numeric": False,
        "size": 0,
    },
    {"id": 69, "name": "NETWORK_CONFIG_RESPONSE_TYPE", "numeric": False, "size": 0},
    {"id": 73, "name": "CONFIG_SETTINGS_TYPE", "numeric": False, "size": 0},
    {"id": 180, "name": "PATIENT_ASSIGNMENT_REQUEST_TYPE", "numeric": False, "size": 0},
    {"id": 41, "name": "STRING_DATA_TYPE", "numeric": False, "size": 0},
    {
        "id": 42,
        "name": "LOGGING_DATA_TYPE",
        "array": "LOGS",
        "numeric": False,
        "header": {"struct": "<HIQBH", "size": 17},
        "numeric": False,
        "size": 0,
    },
    {"id": 1830, "name": "DEVICE_STATUS_TYPE", "numeric": False, "size": 0},
    {"id": 1835, "name": "SESSION_STATUS_TYPE", "numeric": False, "size": 0},
    {"id": 1910, "name": "SYSTEM_NOTIFICATION_TYPE", "numeric": False, "size": 0},
    {"id": 1920, "name": "LOG4J_DATA_TYPE", "numeric": False, "size": 0},
    {"id": 2000, "name": "TUNNEL_ENVELOPE_TYPE", "numeric": False, "size": 0},
    {"id": 2010, "name": "TUNNEL_CONTROL_TYPE", "numeric": False, "size": 0},
    {
        "array": "BATTERY_STATUS",
        "id": 43,
        "name": "BATTERY_DATA_TYPE",
        "numeric": True,
        "size": 26,
        "struct": "<2I4Hh3H",
    },
    {
        "array": "SENSOR_CONNECTION",
        "id": 185,
        "name": "SENSOR_CONNECTION2_TYPE",
        "numeric": True,
        "size": 18,
        "struct": "<3I2H",
    },
    {"id": 209, "name": "VERSION_INFO", "numeric": True, "size": 14, "struct": "<3I"},
    {
        "array": "HR_SCI",
        "id": 210,
        "name": "SCI_HR_NUMERIC",
        "numeric": True,
        "size": 15,
        "struct": "<2IHBbB",
    },
    {
        "array": "HR_BEAT",
        "id": 211,
        "name": "SCI_HR_BEAT",
        "numeric": True,
        "size": 18,
        "struct": "<2IhH3bB",
    },
    {"id": 219, "name": "CUFF_BATTERY_STATUS", "numeric": True, "size": 26},
    {"id": 220, "name": "PP_BATTERY_STATUS", "numeric": True, "size": 26},
    {
        "array": "NIBP_PEAK",
        "id": 221,
        "name": "NIBP_PEAK",
        "numeric": True,
        "size": 17,
        "struct": "<2Iihb",
    },
    {
        "array": "HR_RHYTHM",
        "id": 227,
        "name": "HR_RHYTHM_NUMERIC",
        "numeric": True,
        "size": 21,
        "struct": "<2IHBbBhI",
    },
    {
        "array": "RHYTHM_AFIB",
        "id": 228,
        "name": "AFIB_FEATURES",
        "numeric": True,
        "size": 23,
        "struct": "<3I2ib",
    },
    {
        "array": "RHYTHM_VFIB",
        "id": 229,
        "name": "VFIB_FEATURES",
        "numeric": True,
        "size": 47,
        "struct": "<3I8ib",
    },
    {
        "array": "RED_AC",
        "id": 230,
        "name": "PPG_WAVE_RED_AC2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}H",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "RED_DC",
        "id": 231,
        "name": "PPG_WAVE_RED_AC2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}H",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "IR_AC",
        "id": 232,
        "name": "PPG_WAVE_RED_AC2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}H",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "IR_DC",
        "id": 233,
        "name": "PPG_WAVE_IR_DC2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}H",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "AMBIENT",
        "id": 234,
        "name": "PPG_WAVE_AMBIENT2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}H",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "IR_FILT",
        "id": 235,
        "name": "FILTEREDPPG_WAVE_IR_AC2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}i",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "RED_FILT",
        "id": 236,
        "name": "FILTEREDPPG_WAVE_RED_AC2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}i",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "ECG_I",
        "id": 237,
        "name": "ECG_CHANNEL00_DATA2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}i",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "ECG_II",
        "id": 238,
        "name": "ECG_CHANNEL01_DATA2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}i",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "ECG_III",
        "id": 239,
        "name": "ECG_CHANNEL02_DATA2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}i",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "ECG_AVR",
        "id": 240,
        "name": "ECG_CHANNEL03_DATA2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}i",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "ECG_AVL",
        "id": 241,
        "name": "ECG_CHANNEL04_DATA2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}i",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "ECG_AVF",
        "id": 242,
        "name": "ECG_CHANNEL05_DATA2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}i",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "ECG_V",
        "id": 243,
        "name": "ECG_CHANNEL06_DATA2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}i",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "ECG_V2",
        "id": 244,
        "name": "ECG_CHANNEL07_DATA2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}i",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "ECG_V3",
        "id": 245,
        "name": "ECG_CHANNEL08_DATA2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}i",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "ECG_V4",
        "id": 246,
        "name": "ECG_CHANNEL09_DATA2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}i",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "ECG_V5",
        "id": 247,
        "name": "ECG_CHANNEL10_DATA2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}i",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "ECG_V6",
        "id": 248,
        "name": "ECG_CHANNEL11_DATA2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}i",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "SCG",
        "id": 249,
        "name": "SCG_WAVEFORM2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}h",
        "waveform": {"channels": 3, "version": 2},
    },
    {
        "array": "IP",
        "id": 250,
        "name": "RESP_WAVEFORM2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}i",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "ACC_ECG",
        "id": 251,
        "name": "ACC_ECG2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}h",
        "waveform": {"channels": 3, "version": 2},
    },
    {
        "array": "ACC_ARM",
        "id": 252,
        "name": "ACC_ARM2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}h",
        "waveform": {"channels": 3, "version": 2},
    },
    {
        "array": "ACC_WRT",
        "id": 253,
        "name": "ACC_WT2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}h",
        "waveform": {"channels": 3, "version": 2},
    },
    {
        "array": "OSC",
        "id": 254,
        "name": "CUFF_WAVE_OSC2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}H",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "P1",
        "id": 255,
        "name": "CUFF_WAVE_PRI2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}H",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "array": "P2",
        "id": 256,
        "name": "CUFF_WAVE_SEC2",
        "numeric": False,
        "size": 0,
        "struct": "<{numsamp}H",
        "waveform": {"channels": 1, "version": 2},
    },
    {
        "id": 257,
        "size": 0,
        "header": {"struct": "<I2HQ", "size": 16},
        # packet size [0]
        # device [1]
        # data len [2]
        # subtype [3]
        # time [4]
        "name": "ANALYTICS_TYPE",
        "numeric": False,
    },
    {
        "array": "STALE_DATA",
        "id": 258,
        "name": "STALE_DATA_ALARMS",
        "size": 14,
        "struct": "<2I4B",
        "numeric": True
    },
    #    {
    #        "array": "SOFTWARE_VERSION",
    #        "id": 259,
    #        "name": "SOFTWARE_VERSION",
    #        "size": 44,
    #        "struct": "<2I2B16s4I",
    #        "numeric": True
    #    },
    {
        "array": "RHYTHM_AFIB",
        "id": 3002,
        "name": "AFIB_FEATURES_V2",
        "numeric": True,
        "size": 22,
        "struct": "<2IHI3h"
    },
    {
        "array": "RHYTHM_VFIB",
        "id": 3003,
        "name": "VFIB_FEATURES_V2",
        "numeric": True,
        "size": 34,
        "struct": "<2IHI9h"
    },
    {
        "array": "SPO2_CTRL2",
        "id": 3009,
        "name": "PPG_CONTROL_V2",
        "numeric": True,
        "size": 34,
        "struct": "<2IH2H2BH2BH2B2i"
    },
    {
        "array": "SCG_BEAT",
        "id": 3010,
        "name": "SCG_BEAT",
        "numeric": True,
        "size": 22,
        "struct": "<2IHIHh2B"
    },
    {
        "array": "CNIBP_PRECAL",
        "id": 3011,
        "name": "CNIBP_PRECAL",
        "numeric": True,
        "size": 46,
        "struct": "<2IHIi2fI3Hif"
    },
    {
        "array": "CNIBP_CAL_ALERT",
        "id": 3012,
        "name": "CNIBP_CAL_ALERT",
        "numeric": True,
        "size": 45,
        "struct": "<2IHI2f2hf2ifB"
    },
    {
        "array": "CNIBP_PRECAL",
        "id": 3013,
        "name": "CNIBP_PRECAL_V2",
        "numeric": True,
        "size": 50,
        "struct": "<2IHIi2fI3HifI"
    },
    {"array": "ALARM_STATUS", "id": 100000001, "size": 0, "numeric": True},
]

packet_map = {}
for dt in packetspec:
    packet_map[dt["id"]] = dt

analyticsspec = [
    {
        "array": "ANALYTICS_RSSI",
        "id": 1,
        "name": "ANALYTICS_SUBTYPE_DATA_PKT_RSSI",
        "numeric": True,
        "size": 4,
        "struct": "<h2B",
        "format_str": "ANALYTICS RSSI: RSSI={0} channel={1}",
    },
    {
        "array": "ANALYTICS_CAN",
        "id": 2,
        "name": "ANALYTICS_SUBTYPE_DATA_PKT_CAN",
        "numeric": True,
        "size": 10,
        "struct": "<2I2B",
        "format_str": "ANALYTICS CAN: "
        "Rx0_Counter={0} Rx1_Counter={1} rxError={2}, txError={3}",
    },
    {
        "array": "ANALYTICS_SCREEN",
        "id": 3,
        "name": "ANALYTICS_SUBTYPE_DATA_PKT_SCREEN",
        "numeric": True,
        "size": 2,
        "struct": "<2B",
        "format_str": "ANALYTICS SCREEN: SCREEN:{0}, EVENT:{1}",
    },
    {
        "array": "ANALYTICS_CONNECTION_TRACKER",
        "id": 4,
        "name": "ANALYTICS_SUBTYPE_DATA_PKT_CONNECTION_TRACKER",
        "numeric": True,
        "size": 6,
        "struct": "<HI",
        "format_str": "ANALYTICS CONNECTION TRACKER: Disconnects:{0}, TotalTime:{1}",
    },
    {
        'array': 'ANALYTICS_DISCONNECT_REASON',
        'id': 5,
        'name': 'ANALYTICS_SUBTYPE_DATA_PKT_DISCONNECT_REASON',
        'numeric': True,
        'size': 8,
        'struct': '<2HI',
        'format_str':
            (
                'ANALYTICS DISCONNECT REASON: Disconnects:{0}, '
                'DisconnectReason:{1}, Duration:{2}'
            )
        },
    {
        "array": "SPO2_CTRL2",
        "id": 99,
        "name": "ANALYTICS_SUBTYPE_DATA_PKT_PPG_CONTROL",
        "numeric": True,
        "size": 26,
        "struct": "<I2H2BH2BH2B2i",
        "format_str": "{0}\tANALYTICS SPO2 CTRL: Sensor State: {5}",
    }
]

analytics_map = {}
for dt in analyticsspec:
    analytics_map[dt["id"]] = dt

from . import packets  # noqa
from . import logs  # noqa
from . import chunks  # noqa
from . import util  # noqa

try:
    from . import convert  # noqa
except ImportError:
    warnings.warn(
        "Unable to import sotera.io.visi.convert (this is normal in jython)",
        ImportWarning,
    )
